# Generated by Django 3.0.3 on 2020-02-12 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='login',
            name='role',
            field=models.CharField(default=0, max_length=25),
            preserve_default=False,
        ),
    ]
