# Generated by Django 3.0.3 on 2020-02-13 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmapp', '0002_login_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Addtower',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tower_name', models.CharField(max_length=250)),
                ('tower_location', models.CharField(max_length=250)),
                ('qrcode', models.CharField(max_length=250)),
            ],
        ),
    ]
