# Generated by Django 3.0.3 on 2020-02-29 07:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farmapp', '0002_login_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bay_name', models.CharField(max_length=25)),
                ('qrcode', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Croptype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop_type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Packingtype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('packing_type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Rack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rack_name', models.CharField(max_length=25)),
                ('qrcode', models.CharField(max_length=25)),
                ('fk_bayid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmapp.Bay')),
            ],
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Stages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stages', models.CharField(max_length=50)),
                ('colorcode', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Unitmaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_name', models.CharField(max_length=25)),
            ],
        ),
        migrations.AlterField(
            model_name='login',
            name='password',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='login',
            name='username',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='register',
            name='cpassword',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='register',
            name='email',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='register',
            name='mobile',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='register',
            name='name',
            field=models.CharField(max_length=25),
        ),
        migrations.CreateModel(
            name='Tower',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tower_name', models.CharField(max_length=25)),
                ('tower_location', models.CharField(max_length=25)),
                ('qrcode', models.CharField(max_length=25)),
                ('tower_color', models.CharField(max_length=25)),
                ('tower_height', models.CharField(max_length=25)),
                ('Bay_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmapp.Bay')),
                ('Rack_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmapp.Rack')),
                ('vendor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmapp.Vendor')),
            ],
        ),
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop_name', models.CharField(max_length=25)),
                ('crop_variety', models.CharField(max_length=25)),
                ('crop_desc', models.CharField(max_length=25)),
                ('unit_per_pack', models.CharField(max_length=25)),
                ('crop_duration', models.CharField(max_length=25)),
                ('mid_check', models.CharField(max_length=25)),
                ('no_harvest_cutting', models.CharField(max_length=25)),
                ('regrow_dates', models.CharField(max_length=25)),
                ('first_harvest', models.CharField(max_length=25)),
                ('second_harvest', models.CharField(max_length=25)),
                ('third_harvest', models.CharField(max_length=25)),
                ('fourth_harvest', models.CharField(max_length=25)),
                ('sale_price_wholesale', models.CharField(max_length=25)),
                ('sale_price_farmer', models.CharField(max_length=25)),
                ('sale_price_rest', models.CharField(max_length=25)),
                ('soil_type', models.CharField(max_length=25)),
                ('plant_distance', models.CharField(max_length=25)),
                ('crop_image', models.FileField(blank=True, upload_to='cropimages/', verbose_name='initial_picture')),
                ('temparature', models.CharField(max_length=25)),
                ('crop_type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmapp.Croptype')),
                ('packing_type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmapp.Packingtype')),
                ('season_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmapp.Season')),
                ('unit_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmapp.Unitmaster')),
            ],
        ),
    ]
