# Generated by Django 3.0.3 on 2020-02-27 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmapp', '0003_auto_20200217_1158'),
    ]

    operations = [
        migrations.CreateModel(
            name='Croptype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop_type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Stages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stages', models.CharField(max_length=50)),
                ('colorcode', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Unitmaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_name', models.CharField(max_length=50)),
            ],
        ),
    ]
