# Generated by Django 3.0.3 on 2020-02-28 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmapp', '0004_croptype_season_stages_unitmaster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bay',
            name='bay_name',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='bay',
            name='qrcode',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='login',
            name='password',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='login',
            name='username',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='rack',
            name='qrcode',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='rack',
            name='rack_name',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='register',
            name='cpassword',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='register',
            name='email',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='register',
            name='mobile',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='register',
            name='name',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='tower',
            name='qrcode',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='tower',
            name='tower_color',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='tower',
            name='tower_height',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='tower',
            name='tower_location',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='tower',
            name='tower_name',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='vender',
            name='vender_name',
            field=models.CharField(max_length=25),
        ),
    ]
